# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.6.9"
        cache: "pip"
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    - name: Create .env file
      uses: SpicyPizza/create-envfile@v1.3
      with:
        envkey_BASE_API_URL: "https://beta.check-mot.service.gov.uk/trade/vehicles/"
        envkey_MOT_TESTS_API_URL: "mot-tests?registration="
        envkey_API_KEY: "testapikey"
        directory: .
        file_name: .env
        fail_on_empty: false
    - name: Run tests
      run: |
        python tests.py
